# Site settings
title_left    : "So Tay"
title_right   : "Code" # default: ""
description   : "Blog of Note."
keywords      : "Jekyll, Java, Code, Note"
url           : https://sotaycode.xyz # site url
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "/assets/img/avatar_Bod.png" # image uri like logo/cover image for site seo
timezone      : Asia/Bangkok

google_analytics  : ""
twitter_username  : ""
comments_enabled  : false # if enabled (set to true), please provide your disqus_username
disqus_shortname  : ""
postshare_enabled : false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name        : Tran Tuan # author name
  bio         : >- # tell to the world
    Notes to Myself become to Developer
  #username    : username # general username
  github      : TranDuongNgocTuan # github username
  #twitter     : twitter_username # twitter username
  facebook    : ittuan123 # facebook username
  email       : ittuan123@gmail.com # email adress
  avatar      : /assets/img/avatar_Bod.png # change with your own avatar

# plugins:
#   - jekyll-sitemap
#   - bourbon
#   - jekyll-paginate

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate
  # - jekyll-postfiles

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude:
  - "gulp"
  - "node_modules"
  - "bower"
  - "bower_components"
  - "config.rb"
  - "src"
  - "Gemfile"
  - "Gemfile.lock"
  - ".rvmrc"
  - ".rbenv-version"
  - "package.json"
  - "gulpfile.js"
  - "README.md"
  - "Rakefile"
  - "changelog.md"
  - "script"
  - "vendor"
  - "thinkspace.gemspec"
